CREATE TABLE admins (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ADMIN_NAME VARCHAR(255),
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    EMAIL_ADMIN VARCHAR(255) NOT NULL,
    ABOUT_ADMIN VARCHAR(1500),
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE authors (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AVATAR_AUTHOR VARCHAR(255),
    NAME_AUTHOR VARCHAR(255) NOT NULL,
    ABOUT_AUTHOR VARCHAR(255),
    FACEBOOK VARCHAR(255),
    TWITTER VARCHAR(255),
    INSTAGRAM VARCHAR(255),
    GOOGLE VARCHAR(255),
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_posts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT_ID INT NOT NULL,
    AUTHOR_ID INT NOT NULL,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BLOG_POST_ID INT NOT NULL,
    COMMENT_CONTENT VARCHAR(255) NOT NULL,
    AUTHOR_OF_COMMENT_ID INT NOT NULL,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255) NOT NULL,
    CLIENT_EMAIL VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL,
    DONE INT,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contents (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT_MAIN VARCHAR(255) ,
    HIGHLIGHTS VARCHAR(255) ,
    BULLETS VARCHAR(255) ,
    HEADER_FOTO VARCHAR(255) NOT NULL,
    CONTENT_FOTO VARCHAR(255),
    TAGS VARCHAR(255),
    CATEGORY VARCHAR(255) NOT NULL,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE newsletter (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255) NOT NULL,
    CLIENT_EMAIL VARCHAR(255) NOT NULL,
    AVATAR_USER VARCHAR(255),
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workers_team (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_PHOTO VARCHAR(255) NOT NULL,
    EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    EMPLOYEE_ROLE VARCHAR(255) NOT NULL,
    EMPLOYEE_DEPARTMENT VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FACEBOOK VARCHAR(255),
    LINKEDIN VARCHAR(255),
    STATUS INT NOT NULL,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
