CREATE TABLE admins (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ADMIN_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    LOGIN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    PASSWORD_HASH VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    SALT VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    EMAIL_ADMIN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    ABOUT_ADMIN VARCHAR(1500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE authors (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AVATAR_AUTHOR VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    NAME_AUTHOR VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    ABOUT_AUTHOR VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    FACEBOOK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    TWITER_X VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    INSTAGRAM VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    GOOGLE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_posts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT_ID INT,
    AUTHOR_ID INT,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BLOG_POST_ID VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    COMMENT_CONNTENT VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    BLOG_POST_COMMENT_ID INT,
    AUTHOR_OF_COMMENT_ID INT,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    CLIENT_EMAIL VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    SUBJECT  VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MESSAGE  VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DONE INT,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contents (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    CONTENT_MAIN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    HIGHLIGHTS VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    BULLETS VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    HEADER_FOTO VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    CONTENT_FOTO VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    TAGS VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    CATEGORY VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE newsletter (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    CLIENT_EMAIL VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    AVATAR_USER VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workers_team (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_PHOTO VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    EMPLOYEE_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    EMPLOYEE_ROLE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    EMPLOYEE_DEPARTMENT VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    PHONE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    EMAIL VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    FACEBOOK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    LINEDIN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);